### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by attah** [attah/harbour-splay#3]
Make an icon.

**Comment by JSEHV** [comment]
Is one of these icon designs suiting your vision of the app?
The shared link contains the svg and the png files.

https://ufile.io/pi83j

![harbour-sr-black](https://user-images.githubusercontent.com/5128988/50048005-9b8e6780-00c1-11e9-8c8d-7eb40e662acd.png)
![harbour-sr-colors](https://user-images.githubusercontent.com/5128988/50048023-f9bb4a80-00c1-11e9-9df8-7c0e9182db99.png)
![harbour-sr-flag](https://user-images.githubusercontent.com/5128988/50048006-9b8e6780-00c1-11e9-8232-47bcc97214a6.png)
![harbour-sr-logo](https://user-images.githubusercontent.com/5128988/50048007-9c26fe00-00c1-11e9-8c0f-286c40e663a5.png)
![harbour-sr-shape](https://user-images.githubusercontent.com/5128988/50048008-9c26fe00-00c1-11e9-80ca-eb07078d2995.png)

**Comment by attah** [comment]
Yes, if i sort out what is OK to use... I was also looking at finding some cursive script or SR-like font and just putting S'Play on the icon, but didn't find something i liked. I should ask on their forum if this would be ok to use.

**Comment by JSEHV** [comment]
I really like the one with the flag, gives it a nice Swedish touch. Worked them out in all sizes (see link below). Maybe nice for the first version in the harbour store. You can always update it with a next release :)

The lasts 2 (with eSRa in it) are the ones they use themselves in the Android and iOS App Store.
So I guess those are not the preferred ones to use.

https://ufile.io/yhhtl

![harbour-sr-flag-172x172](https://user-images.githubusercontent.com/5128988/50048096-dee9d580-00c3-11e9-896d-23eed2345d74.png)

**Comment by attah** [comment]
I'm pretty sure changing the background is frowned upon. Trying to work out the legalities in general too (email sent to the contact person for graphics). Personally i think it is a little too Swedish (quite a Swedish thing to think :) A flag in the corner or in a single text element (probably also frowned upon), would look neater imo. I too prefer SR one to eSRa, but apparently that's how they brand themselves.

**Comment by JSEHV** [comment]
Maybe this is a legally allowed, colors and country respecting, elements/text including, Sailfish design respecting logo. Even if you squint your eyes, the leg of the R looks a bit like an antenna. Not intended, but still, nice if you see it (I think).

![harbour-sr-radio-172x172](https://user-images.githubusercontent.com/5128988/50053735-66722b80-013a-11e9-8834-d4a06e0e5fd7.png)

All sizes

[harbour-sr-radio.zip](https://github.com/attah/harbour-splay/files/2683552/harbour-sr-radio.zip)

**Comment by attah** [comment]
Nice! I'll see what reply i get...

**Comment by attah** [comment]
Reply has arrived, and it says that i may not use the logo.

**Comment by JSEHV** [comment]
A neutral one? Without SR? Colors are still useful/nice in my view.
You tell me... What do you prefer?

**Comment by attah** [comment]
That would work well i think. I'm still not entirely past my idea of cursive-on-black, but i need to learn to use colors. :) This one is indeed very clear and distinct.

**Comment by JSEHV** [comment]
Ideas... I like the second one even more... minimalistic, suits Sailfish OS design (and I think the Swedish can appreciate it too)

![harbour-swe-radio-128x128](https://user-images.githubusercontent.com/5128988/50109180-5be98c00-0237-11e9-8eda-59129abf5dd7.png)
![harbour-sr-minimal2](https://user-images.githubusercontent.com/5128988/50109557-7a03bc00-0238-11e9-8293-b38f9b1cc868.png)
![harbour-sr-minimal2a](https://user-images.githubusercontent.com/5128988/50110877-9e14cc80-023b-11e9-8211-170c7d842a5c.png)

**Comment by attah** [comment]
That second one pretty cool actually, let's go for that one! :+1:

**Comment by JSEHV** [comment]
Here are nr.2 and nr.3 :)

[harbour-sr-minimal.zip](https://github.com/attah/harbour-splay/files/2687612/harbour-sr-minimal.zip)
[harbour-sr-minimal-white.zip](https://github.com/attah/harbour-splay/files/2687613/harbour-sr-minimal-white.zip)

Looking forward to see the app in Jolla's Harbour App Store.

**Comment by attah** [comment]
Did you have to make it so hard to choose? :slightly_smiling_face: 
I think I'll try the white one.
